### ISSUE TITLE
handle tiktok shortened links.

### ISSUE THREAD

**Issue by derspyy** [httpjamesm/launchpad-redirects#12]
there are tiktok shortened links that follow this format: `https://vm.tiktok.com/<video>/` and `https://vt.tiktok.com/<video>/`.

proxitok handles these by using a placeholder @: `https://cringe.whatever.social/@placeholder/video/<video>/`.

it would be interesting for these to be handled. : )

https://github.com/pablouser1/ProxiTok/blob/19a2066fc2aa33f423b66c0b65c89ddfe1dc3234/app/Controllers/RedirectController.php#L73-L76

**Comment by privacytime101** [comment]
Fixed in #16

**Comment by piuvas** [comment]
this is not resolved since the placeholder is not added and `vm` and `vt` links are improperly resolved.

made this shitty pr: httpjamesm/launchpad-redirects#17
